import Providers from "@/components/Providers";
import "./globals.css";
import Appbar from "@/components/Appbar";
import type { Metadata } from "next";
import { cn } from "@/lib/utils"
import { ToastContainer } from "react-toastify";
import { Inter } from "next/font/google";


const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        inter.className
      )}>
        <Providers>
          <Appbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
