import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import Dasboard from "@/components/dashboard/Dasboard";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const Dashbpardlayout = async ({ children }: { children: React.ReactNode }) => {
    return (
        <div className="bg-slate-900">
            <div className="">
                <Dasboard />
            </div>
            <div>
                <ToastContainer />
            </div>
            <div className="w-full p-5 ">{children}</div>
        </div>
    );
};

export default Dashbpardlayout;