import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
import { cn } from "@/lib/utils"
import { ToastContainer } from "react-toastify";
import Dasboard from "@/components/dashboard/Dasboard";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={cn(
                "min-h-screen bg-background font-sans antialiased",
                inter.className
            )}>
                <div className="flex h-screen flex-row   md:overflow-hidden">
                    <div className=" ">
                        <Dasboard />
                    </div>

                    <div className="w-full p-5 ">{children}</div>
                    <div>
                        <ToastContainer />
                    </div>
                </div>
            </body>
        </html>
    );
}
